name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Permissão no mvnw
        run: chmod +x mvnw

      - name: Build com Maven
        run: ./mvnw clean package -DskipTests

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PWD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build e Push da imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            enzoanthony/notification-service:v${{ github.run_number }}
            enzoanthony/notification-service:latest